### ISSUE TITLE
Allow the input data to be specified as a command line argument.

### ISSUE THREAD

**Issue by kruschk** [aspera-non-spernit/guru#3]
The input data filename and location is currently hard-coded into the `utils` module. It should instead be specified as a command line argument. For example, the program should be callable with `$ guru <error> <input-file>`.

**Comment by aspera-non-spernit** [comment]
Fixed that. Using clap to collect the args from the cli. 

Renamed --input to --data for the (training) data. Input could mean input for the training data and the persistent network.
